FIELDS = [
    "kjNo", "uktkYmd", "shkiKigenHi", "juriAtsh", "kjKbn",
    "onlinJishuOboUktkKahi", "sngBrui", "tryKoyoKibo", "jgshNo",
    "jgshMeiKana", "jgshMei", "szciYbn", "szci", "sksu", "shigotoNy",
    "koyoKeitai", "hakenUkeoiToShgKeitai", "hakenUkeoiToRdsha",
    "koyoKikan", "shgBs", "shgBsYubinNo", "shgBsJusho", "shgBsMyorEki",
    "shgBsKotsuShudan", "shgBsShyoJn", "shgBsKitsuTsak", "mycarTskn",
    "tenkinNoKnsi", "nenreiSegn", "nenreiSegnHanni", "nenreiSegnGaitoJiyu",
    "nenreiSegnNoRy", "grki", "hynaKiknt", "hynaKikntShsi", "hynaMenkyoSkku",
    "trialKikan", "chgn", "khky", "tgktNiShwrTat", "koteiZngyKbn",
    "thkinRodoNissu", "chgnKeitaiToKbn", "tsknTat", "chgnSkbi", "chgnSrbi",
    "chgnSrbiTsuki", "chgnSrbiHi", "shokyuSd", "shokyuMaeNendoJisseki",
    "sokkgSkrt", "shoyoSdNoUmu", "shoyoMaeNendoUmu", "shoyoMaeNendKaisu",
    "shoyoKingaku", "shgJn1", "jkgiRodoJn", "thkinJkgiRodoJn", "sanrokuKyotei",
    "kyukeiJn", "nenkanKjsu", "kyjs", "shukFtskSei", "kyjsSnta", "nenjiYukyu",
    "knyHoken", "tskinKsi", "tskinSd", "tskinSdKinzokuNensu", "tnsei",
    "tnseiTeinenNenrei", "saiKoyoSd", "kmec", "nkj", "nkjTkjk",
    "riyoKanoTkjShst", "jgisKigyoZentai", "jgisShgBs", "jgisUchiJosei",
    "jgisUchiPart", "setsuritsuNen", "shkn", "rodoKumiai", "jigyoNy",
    "kaishaNoTokucho", "yshk", "dhshaMei", "hoNinNo", "fltmShgKisoku",
    "partShgKisoku", "ikujiKyugyoStkJisseki", "kaigoKyugyoStkJisseki",
    "kangoKyukaStkJisseki", "gkjnKoyoJisseki", "saiyoNinsu", "boshuRy",
    "selectHoho", "selectKekkaTsuch", "shoruiSelectKekka", "mensetsuSelectKekka",
    "ksshEnoTsuchiHoho", "selectNichijiTo", "selectBsYubinNo", "selectBsJusho",
    "selectBsMyorEki", "selectBsMyorEkiKotsuShudan", "selectBsShyoJn",
    "oboShoruitou", "oboShoruiNoSofuHoho", "yusoNoSofuBsYubinNo",
    "yusoNoSofuBsJusho", "obohen", "ttsYkm", "ttsTts", "ttsTel", "ttsFax",
    "kjTkjk", "shokumuKyuSd", "shokumuKyuSdNoNy", "fukushokuSd", "fukushokuSdNoNy"
]
